### ISSUE TITLE
[S3 - PBI36] Tambah Data Supplier

### ISSUE THREAD

**Issue by syukronkamil** [SI-RPL-2021/SI4201--WHMARKET#44]
saya sebagai admin ingin menambahkan data supplier menggunakan action tambah sehingga bisa menambahkan datanya dari daftar tabel.

![image](https://user-images.githubusercontent.com/71879419/123118842-2f98d100-d46d-11eb-8af5-a203f1b37ac1.png)

Flow:

1. Klik action tambah data supplier
2. Masukan data sesuai yang telah diperintahkan pada page tambah data supplier
3. Jika sudah sesuai dapat mengklik submit.
4. Data supplier pun berhasil ditambahkan

**Comment by jonathanbonar** [comment]
saya ingin menambhakan data supplier di kolom data suplier
![image](https://user-images.githubusercontent.com/71879419/121183970-d0dd3000-c88e-11eb-8641-c3953ec513ed.png)
