### ISSUE TITLE
[S2- PBI8] Pemeriksaan Barang

### ISSUE THREAD

**Issue by HadinaWawesi** [SI-RPL-2021/SI4201--WHMARKET#5]
saya sebagai pegawai ingin melakukan input data barang kadaluarsa di toko sehingga bisa melakukan pencatatan barang  kadaluarsa dan yang tidak.

![image](https://user-images.githubusercontent.com/71879419/123121056-0ed17b00-d46f-11eb-9bae-70ad7fab1fc4.png)

1.  Pegawai masuk ke dalam halaman Pemeriksaan Barang
2.  Sistem menampilkan halaman Pemeriksaan Barang
3.  Pegawai klik button Tambah Pemeriksaan Barang
4.  Sistem menampilkan halaman Tambah Pemeriksaan Barang
5.  Pegawai memasukkan data sesuai form

**Comment by Wikafajriahr** [comment]
Mockup menyusul

**Comment by HadinaWawesi** [comment]
![S__33792058](https://user-images.githubusercontent.com/71918202/111859532-2d0d7380-8974-11eb-8c6e-44d5a8e4a601.jpg)
![S__33792066](https://user-images.githubusercontent.com/71918202/111859534-2f6fcd80-8974-11eb-9ec5-c6031640c746.jpg)
![S__33792065](https://user-images.githubusercontent.com/71918202/111859536-31d22780-8974-11eb-9e21-821bf766db90.jpg)
