### ISSUE TITLE
[S3 - PBI10] Data Pegawai

### ISSUE THREAD

**Issue by Wikafajriahr** [SI-RPL-2021/SI4201--WHMARKET#6]
saya sebagai admin ingin mengelola data pegawai sehingga data pegawai bisa ditambah, dihapus, maupun diedit.

**Comment by Wikafajriahr** [comment]
![1616171060368](https://user-images.githubusercontent.com/71864726/111812231-7f19af00-890a-11eb-9089-949d0605a6db.jpg)

**Comment by adhityapaf** [comment]
Duplicate issue with #50
